### ISSUE TITLE
Performance Profiling Results

### ISSUE THREAD

**Issue by Pugins** [EltonLi2000/IllumiGator#37]
As the number of rays are increased the geometry's get_intersection() becomes the programs bottleneck. This is the result of the number of calls to get_intersection() increasing dramatically as the number of rays increase. At 1000 rays, nearly 39% of all function calls were get_intersection. About 38% of the programs total running time was spent calculating intersections.

Another computationally expensive function was cast_ray().

**Comment by BigDomas** [comment]
Working on SIMD optimizations using numpy
