### ISSUE TITLE
Light reflection

### ISSUE THREAD

**Issue by EltonLi2000** [EltonLi2000/IllumiGator#6]

**Comment by amberhandal** [comment]
Each mirror object can now have at least one side that accurately depicts reflection using the reflection formula to find the vector normal to the side of the mirror the the ray is hitting and create a child vector that reflects from that point in the calculated direction. Each subsequent ray will be a child of the previous and either be a reflected ray, a refracted ray, a colored ray, or null if hitting a non-interactive object.
