### ISSUE TITLE
Polish Levels

### ISSUE THREAD

**Issue by Pugins** [EltonLi2000/IllumiGator#96]
- Remove moving block from Level 1
- Level 2 is too finnicky. **Possible solution:** move two narrowing blocks further from lens. Remove single moving block.
- Some level 3 walls are unaligned.
- Level 4 _left_ route needs tweaking. Maybe remove one of the three moving blocks and move florida man?

**Comment by dakota-cappel** [comment]
Polished levels 2-4, using the suggestions above. Level 4 Florida Man has been moved up and right a little.
